/*
 Generated by typeshare 1.13.4
*/

/** ポケモン登録リクエストDTO */
export interface CreatePokemonRequestDto {
	pokemon_name: string;
	pokemon_name_jp: string;
	nickname?: string;
	terastal_type: string;
	ev_hp: number;
	ev_attack: number;
	ev_defense: number;
	ev_special_attack: number;
	ev_special_defense: number;
	ev_speed: number;
	iv_hp: number;
	iv_attack: number;
	iv_defense: number;
	iv_special_attack: number;
	iv_special_defense: number;
	iv_speed: number;
	nature: string;
	ability: string;
	held_item?: string;
	moves: string[];
}

/** ポケモン登録レスポンスDTO */
export interface CreatePokemonResponseDto {
	pokemon_id: string;
	user_id: string;
	nickname?: string;
	form_id: number;
	species_id: number;
	fullname: string;
	fullname_jp: string;
}

/** チーム作成リクエストDTO */
export interface CreateTeamRequestDto {
	team_name: string;
}

/** チーム作成レスポンスDTO */
export interface CreateTeamResponseDto {
	team_id: string;
	owner_id: string;
	team_name: string;
}

/** エラーレスポンスDTO */
export interface ErrorResponseDto {
	error: string;
	error_code: string;
}

/** 習得可能な技DTO */
export interface LearnableMoveDto {
	move_id: number;
	name: string;
	name_ja?: string;
	type?: string;
	power?: number;
	accuracy?: number;
	pp?: number;
	damage_class?: string;
	usage_rate?: number;
}

/** ログインリクエストDTO */
export interface LoginRequestDto {
	email: string;
	password: string;
}

/** マッチアップDTO（有利/不利情報） */
export interface MatchupDto {
	/** 対戦相手のform_id */
	opponent_form_id: number;
	/** 対戦相手の英語名 */
	opponent_name: string;
	/** 対戦相手の日本語名 */
	opponent_name_ja?: string;
	/** 対戦回数 */
	n: number;
	/** KO/Switch確率（0-1） */
	p: number;
	/** 標準偏差 */
	d: number;
}

/** マトリクス表示用のポケモン情報 */
export interface MatrixPokemonDto {
	form_id: number;
	name: string;
	name_ja?: string;
	is_setup: boolean;
}

/** マトリクスのセル情報 */
export interface MatrixCellDto {
	form_id: number;
	opponent_form_id: number;
	p: number;
	n: number;
}

/** マッチアップマトリクスDTO */
export interface MatchupMatrixDto {
	pokemon: MatrixPokemonDto[];
	cells: MatrixCellDto[];
}

/** マッチアップ一覧DTO */
export interface MatchupsDto {
	/** 有利なマッチアップ（p > 0.5） */
	favorable: MatchupDto[];
	/** 不利なマッチアップ（p < 0.5） */
	unfavorable: MatchupDto[];
}

/** ポケモンデータDTO */
export interface PokemonDataDto {
	pokemon_name: string;
	terastal_type: string;
	ev_hp: number;
	ev_attack: number;
	ev_defense: number;
	ev_special_attack: number;
	ev_special_defense: number;
	ev_speed: number;
	iv_hp: number;
	iv_attack: number;
	iv_defense: number;
	iv_special_attack: number;
	iv_special_defense: number;
	iv_speed: number;
	nature: string;
	ability: string;
	held_item?: string;
	moves: string[];
}

/** エラーレスポンスDTO */
export interface PokemonErrorResponseDto {
	error: string;
}

/** ポケモンマスタデータDTO */
export interface PokemonMasterDto {
	form_id: number;
	species_id: number;
	fullname: string;
	fullname_ja?: string;
	type1: string;
	type2?: string;
	hp: number;
	attack: number;
	defense: number;
	sp_attack: number;
	sp_defense: number;
	speed: number;
	usage?: number;
	raw_count?: number;
	is_setup?: boolean;
}

/** ポケモンレスポンスDTO */
export interface PokemonResponseDto {
	fullname: string;
	fullname_jp: string;
	form_id: number;
	species_id: number;
}

/** ポケモンレスポンスDTO */
export interface PokemonResponseDto {
	pokemon_id: string;
	user_id: string;
	nickname?: string;
	form_id: number;
	species_id: number;
	fullname: string;
	fullname_jp: string;
	type1: string;
	type2?: string;
	type1_jp: string;
	type2_jp?: string;
	terastal_type: string;
	terastal_type_jp: string;
	ev_hp: number;
	ev_attack: number;
	ev_defense: number;
	ev_special_attack: number;
	ev_special_defense: number;
	ev_speed: number;
	iv_hp: number;
	iv_attack: number;
	iv_defense: number;
	iv_special_attack: number;
	iv_special_defense: number;
	iv_speed: number;
	nature: string;
	nature_jp?: string;
	ability: string;
	ability_jp?: string;
	held_item?: string;
	held_item_jp?: string;
	moves: string[];
	moves_jp: string[];
	moves_types: string[];
}

/** 使用率詳細データDTO */
export interface UsageDetailDto {
	name: string;
	name_ja?: string;
	percentage: number;
}

/** ポケモン使用率統計DTO */
export interface PokemonUsageStatsDto {
	form_id: number;
	moves: UsageDetailDto[];
	items: UsageDetailDto[];
	abilities: UsageDetailDto[];
	tera_types: UsageDetailDto[];
	natures: UsageDetailDto[];
}

/** リフレッシュリクエストDTO */
export interface RefreshRequestDto {
	refresh_token: string;
}

/** シンプルトークンレスポンスDTO（refresh用、refresh_tokenはCookieで返す） */
export interface RefreshResponseDto {
	access_token: string;
	token_type: string;
	expires_in: number;
}

/** ユーザー登録リクエストDTO */
export interface RegisterRequestDto {
	username: string;
	email: string;
	password: string;
}

/** ユーザー登録レスポンスDTO */
export interface RegisterResponseDto {
	user_id: string;
	username: string;
	email: string;
}

export interface SuggestedPokemonDto {
	form_id: number;
	name: string;
	name_ja?: string;
	is_setup: boolean;
	score: number;
	covered_threats: MatrixPokemonDto[];
}

/** LLMによる説明付きの提案ポケモン */
export interface SuggestedPokemonWithReasoningDto {
	form_id: number;
	name: string;
	name_ja?: string;
	is_setup: boolean;
	score: number;
	covered_threats: MatrixPokemonDto[];
	reasoning?: string;
}

/** エラーレスポンスDTO (Team用) */
export interface TeamErrorResponseDto {
	error: string;
}

/** チームレスポンスDTO */
export interface TeamResponseDto {
	team_id: string;
	owner_id: string;
	team_name: string;
	pokemon: PokemonResponseDto[];
}

export interface TeamSuggestionResponseDto {
	all_threats: MatrixPokemonDto[];
	axis_pokemon: SuggestedPokemonDto[];
	suggestions: SuggestedPokemonDto[];
}

/** LLM説明付きチーム提案レスポンス */
export interface TeamSuggestionWithReasoningResponseDto {
	all_threats: MatrixPokemonDto[];
	axis_pokemon: SuggestedPokemonDto[];
	suggestions: SuggestedPokemonWithReasoningDto[];
}

/** トークンレスポンスDTO (refresh_tokenはCookieで返すため除外) */
export interface TokenResponseDto {
	user_id: string;
	username: string;
	email: string;
	access_token: string;
	token_type: string;
	expires_in: number;
}

/** ポケモン更新リクエストDTO */
export interface UpdatePokemonRequestDto {
	nickname?: string;
	terastal_type: string;
	ev_hp: number;
	ev_attack: number;
	ev_defense: number;
	ev_special_attack: number;
	ev_special_defense: number;
	ev_speed: number;
	iv_hp: number;
	iv_attack: number;
	iv_defense: number;
	iv_special_attack: number;
	iv_special_defense: number;
	iv_speed: number;
	nature: string;
	ability: string;
	held_item?: string;
	moves: string[];
}

/** チーム更新リクエストDTO */
export interface UpdateTeamRequestDto {
	team_name?: string;
	pokemon?: PokemonDataDto[];
}

