/*
 Generated by typeshare 1.13.4
*/

/** ポケモン登録リクエストDTO */
export interface CreatePokemonRequestDto {
	pokemon_name: string;
	pokemon_name_jp: string;
	nickname?: string;
	terastal_type: string;
	ev_hp: number;
	ev_attack: number;
	ev_defense: number;
	ev_special_attack: number;
	ev_special_defense: number;
	ev_speed: number;
	iv_hp: number;
	iv_attack: number;
	iv_defense: number;
	iv_special_attack: number;
	iv_special_defense: number;
	iv_speed: number;
	nature: string;
	ability: string;
	held_item?: string;
	moves: string[];
}

/** ポケモン登録レスポンスDTO */
export interface CreatePokemonResponseDto {
	pokemon_id: string;
	user_id: string;
	nickname?: string;
	form_id: number;
	species_id: number;
	fullname: string;
	fullname_jp: string;
}

/** チーム作成リクエストDTO */
export interface CreateTeamRequestDto {
	team_name: string;
}

/** チーム作成レスポンスDTO */
export interface CreateTeamResponseDto {
	team_id: string;
	owner_id: string;
	team_name: string;
}

/** エラーレスポンスDTO */
export interface ErrorResponseDto {
	error: string;
	error_code: string;
}

/** ログインリクエストDTO */
export interface LoginRequestDto {
	email: string;
	password: string;
}

/** ポケモンデータDTO */
export interface PokemonDataDto {
	pokemon_name: string;
	terastal_type: string;
	ev_hp: number;
	ev_attack: number;
	ev_defense: number;
	ev_special_attack: number;
	ev_special_defense: number;
	ev_speed: number;
	iv_hp: number;
	iv_attack: number;
	iv_defense: number;
	iv_special_attack: number;
	iv_special_defense: number;
	iv_speed: number;
	nature: string;
	ability: string;
	held_item?: string;
	moves: string[];
}

/** エラーレスポンスDTO */
export interface PokemonErrorResponseDto {
	error: string;
}

/** ポケモンマスタデータDTO */
export interface PokemonMasterDto {
	form_id: number;
	species_id: number;
	fullname: string;
	fullname_ja?: string;
	type1: string;
	type2?: string;
	hp: number;
	attack: number;
	defense: number;
	sp_attack: number;
	sp_defense: number;
	speed: number;
	usage?: number;
	raw_count?: number;
}

/** ポケモンマスタデータDTO */
export interface PokemonMasterDto {
	form_id: number;
	species_id: number;
	fullname: string;
	fullname_ja?: string;
	type1: string;
	type2?: string;
	hp: number;
	attack: number;
	defense: number;
	sp_attack: number;
	sp_defense: number;
	speed: number;
	usage?: number;
	raw_count?: number;
}

/** ポケモンマスタデータレスポンス */
export interface PokemonMasterResponseDto {
	pokemon: PokemonMasterDto[];
	total: number;
}

/** ポケモンレスポンスDTO */
export interface PokemonResponseDto {
	pokemon_id: string;
	user_id: string;
	nickname?: string;
	form_id: number;
	species_id: number;
	fullname: string;
	fullname_jp: string;
	terastal_type: string;
	ev_hp: number;
	ev_attack: number;
	ev_defense: number;
	ev_special_attack: number;
	ev_special_defense: number;
	ev_speed: number;
	iv_hp: number;
	iv_attack: number;
	iv_defense: number;
	iv_special_attack: number;
	iv_special_defense: number;
	iv_speed: number;
	nature: string;
	ability: string;
	held_item?: string;
	moves: string[];
}

/** ポケモンレスポンスDTO */
/** ポケモンレスポンスDTO */
export interface PokemonResponseDto {
	fullname: string;
	fullname_jp: string;
	form_id: number;
	species_id: number;
	terastal_type: string;
	ev_hp: number;
	ev_attack: number;
	ev_defense: number;
	ev_special_attack: number;
	ev_special_defense: number;
	ev_speed: number;
	iv_hp: number;
	iv_attack: number;
	iv_defense: number;
	iv_special_attack: number;
	iv_special_defense: number;
	iv_speed: number;
	nature: string;
	ability: string;
	held_item?: string;
	moves: string[];
}

/** リフレッシュリクエストDTO */
export interface RefreshRequestDto {
	refresh_token: string;
}

/** シンプルトークンレスポンスDTO（refresh用、refresh_tokenはCookieで返す） */
export interface RefreshResponseDto {
	access_token: string;
	token_type: string;
	expires_in: number;
}

/** ユーザー登録リクエストDTO */
export interface RegisterRequestDto {
	username: string;
	email: string;
	password: string;
}

/** ユーザー登録レスポンスDTO */
export interface RegisterResponseDto {
	user_id: string;
	username: string;
	email: string;
}

/** エラーレスポンスDTO (Team用) */
export interface TeamErrorResponseDto {
	error: string;
}

/** チームレスポンスDTO */
export interface TeamResponseDto {
	team_id: string;
	owner_id: string;
	team_name: string;
	pokemon: PokemonResponseDto[];
}

/** トークンレスポンスDTO (refresh_tokenはCookieで返すため除外) */
export interface TokenResponseDto {
	user_id: string;
	username: string;
	email: string;
	access_token: string;
	token_type: string;
	expires_in: number;
}

/** ポケモン更新リクエストDTO */
export interface UpdatePokemonRequestDto {
	nickname?: string;
	terastal_type: string;
	ev_hp: number;
	ev_attack: number;
	ev_defense: number;
	ev_special_attack: number;
	ev_special_defense: number;
	ev_speed: number;
	iv_hp: number;
	iv_attack: number;
	iv_defense: number;
	iv_special_attack: number;
	iv_special_defense: number;
	iv_speed: number;
	nature: string;
	ability: string;
	held_item?: string;
	moves: string[];
}

/** チーム更新リクエストDTO */
export interface UpdateTeamRequestDto {
	team_name?: string;
	pokemon?: PokemonDataDto[];
}

